### ISSUE TITLE
milk bottles datasets and Ontology

### ISSUE THREAD

**Issue by hahapt** [autodistill/autodistill#51] opened 2023-09-21 09:10 UTC
I want to reproduce the whole autodistill process with your demo video about milk bottle. Can you tell that where to get milk bottle dataset and what the 'Ontology' you set?

**Comment by capjamesg** [comment] 2023-09-21 09:22
We have a Notebook you can use to re-create our example project: https://github.com/roboflow/notebooks/blob/main/notebooks/how-to-auto-train-yolov8-model-with-autodistill.ipynb

The ontology is in that Notebook. There is a command in there that lets you download the milk bottle data.

Generally, we use stock image footage sites (i.e. [Pexels](https://www.pexels.com/)) to collect images and videos for use in examples.

**Comment by capjamesg** [comment] 2023-09-21 09:23
We also have an accompanying video that walks through the Notebook: https://www.youtube.com/watch?v=gKTYMfwPo4M

**Comment by hahapt** [comment] 2023-09-21 09:59
Is there any evaluation results about the milk bottle dataset that I can compare with my own training model?

**Comment by capjamesg** [comment] 2023-09-21 10:31
The Notebook contains a confusion matrix:

![Untitled](https://github.com/autodistill/autodistill/assets/37276661/368bde9e-8b9c-49d3-9dc2-a16eef63800b)

If you are looking for more metrics, you will need to run the notebook.

**Comment by capjamesg** [comment] 2023-11-01 12:29
I am closing this Issue since there have been no further comments and I think the issue is addressed above. If you have more questions, let me know!

**Closed by capjamesg** 2023-11-01 12:29 UTC
